.PHONY: clean All

All:
	@echo "----------Building project:[ TP1 - Debug ]----------"
	@cd "TP1" && "$(MAKE)" -f  "TP1.mk"
clean:
	@echo "----------Cleaning project:[ TP1 - Debug ]----------"
	@cd "TP1" && "$(MAKE)" -f  "TP1.mk" clean
